backend:
  name: git-gateway
  branch: content # Branch to update (optional; defaults to master)
# This line should *not* be indented
media_folder: "en/images/thumbs" # Media files will be stored in the repo under images/uploads
public_folder: "/en/images/thumbs"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "en/_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}/{{month}}/{{day}}/{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    identifier_field: slug
    fields: # The fields for each document, usually in front matter
      - { label: "Alternate language page url", name: "altLangPage", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description",  widget: "string" }
      - { label: "Thumbnail image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    folder: "pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

logo_url: https://wet-boew.github.io/themes-dist/GCWeb/GCWeb/assets/sig-blk-en.svg
publish_mode: editorial_workflow
site_url: https://blog.canada.ca